import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Stars from './components/stars';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Personal Site',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Stars />
        {children}
      </body>
    </html>
  )
}
